#This is a clab YAML file
# topology documentation: https://github.com/ron-nersc/UND-NERSC-Collaboration
#Information contained within this script is for the UND and NERSC collaboration team.
#Author: Ronal Kumar [ron@lbl.gov]
#            \
#             \
#              ^__^
#              (oo)\_______
#              (__)        )\
#                 ||----- |
#                 ||     ||
#
# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

global:
  scrape_interval: 5s

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:
  - job_name: "gnmic"
    static_configs:
      - targets: ["gnmic:9273"]